services:
  redis:
    image: redis
    container_name: redis-server
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    # env_file:
    #   - ./backend/.env.dev
    env_file:
      - ./backend/.env.prod
    depends_on:
      - redis
    ports:
      - 8080:8080
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/ui
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    restart: always
    expose:
      - "127.0.0.1:8081:3000"
    networks:
      - app-network
volumes:
  redis_data:


networks:
  app-network:
    driver: bridge
