version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend/ui
      dockerfile: dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:9-alpine
    ports:
      - "6379:6379"
